# -*- coding: utf-8 -*-
"""Análisis de venta de edificios en Connecticut.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBvdit3-CCjwPIUkI7i4Uc3ouXGn2_hr

# Análisis de venta de edificios en Connecticut

En el mundo actual de los negocios, la capacidad de analizar datos de manera efectiva se ha convertido en una habilidad esencial para la toma de decisiones. En este sentido, vamos a realizar un análisis de los datos de ventas de edificios de Connecticut para comprender el comportamiento del mercado inmobiliario en la región.

Para llevar a cabo este análisis, utilizaremos las bibliotecas Pandas y Pyspark, reconocidas por su eficacia en la extracción y transformación de datos. Estas herramientas nos permitirán manejar grandes volúmenes de información de manera eficiente, facilitando la identificación de tendencias y patrones significativos en los datos de ventas.

Además, para la visualización de los resultados, haremos uso de las bibliotecas Seaborn, Matplotlib y Plotly. Estas herramientas nos brindarán la posibilidad de crear gráficos claros y concisos que nos ayudarán a comunicar efectivamente los hallazgos de nuestro análisis.

En resumen, el análisis de los datos de ventas de edificios de Connecticut nos permitirá obtener información valiosa sobre el mercado inmobiliario en la región, lo cual nos ayudará a tomar decisiones estratégicas fundamentadas en datos sólidos. Gracias a la combinación de herramientas como Pandas, Pyspark, Seaborn, Matplotlib y Plotly, estaremos en una posición óptima para realizar un análisis exhaustivo y riguroso que nos permita maximizar el valor de la información obtenida.
"""

!pip install pyspark

from pyspark.sql import SparkSession #Sesión para uso de spark
import pyspark.sql.functions as F #Funciones spark
import pandas as pd #Tratamiento data
import seaborn as sns #Gráficos
import matplotlib.pyplot as plt #Gráficos
from urllib.request import urlopen #Cargado de información en línea
import json #Análisis de archivos Json
import plotly.express as px #Graficación de mapas

spark = SparkSession.builder.master("local") \
                    .appName('Sales_Analysis') \
                    .getOrCreate()

data=spark.read.csv("Real_Estate_Sales_2001-2020_GL.csv",header=True)

data.show()

data.printSchema()

"""Realizamos la conversión de los datos numéricos. Dado que no se definió un esquema al cargar la información con Apache Spark, la mayoría de los datos se interpretaron como tipo string de forma predeterminada. Por lo tanto, es fundamental realizar esta conversión para asegurar el manejo adecuado de los datos numéricos durante el análisis. Este paso es esencial para garantizar la precisión y fiabilidad de los resultados en las siguientes etapas del análisis de datos."""

#Actualización de datos
data = (data.withColumn("List Year",F.col("List Year").cast("int")) #Entero
            .withColumn("Date Recorded",F.to_date(F.col("Date Recorded"),"MM/dd/yyyy")) #Tipo Fecha
            .withColumn("Assessed Value",F.col("Assessed Value").cast("int")) #Entero
            .withColumn("Sale Amount",F.col("Sale Amount").cast("float")) #Decimal
            .withColumn("Sales Ratio",F.col("Sales Ratio").cast("float"))) #Decimal

"""# Análisis de Métricas y Calidad de Datos

En el análisis de métricas y calidad de datos, es crucial contar los valores nulos en el conjunto de datos. Esta información ayuda a evaluar la integridad de los datos y decidir si se necesitan imputar valores o aplicar otras estrategias para manejar los faltantes.

Además, es importante explorar variables de tipo string y generar una muestra de los valores únicos. Este análisis ofrece una visión detallada de la estructura y diversidad de los datos categóricos, fundamental para comprender las categorías presentes y su distribución en el conjunto de datos.

En resumen, un análisis detallado de métricas y calidad de datos proporciona información valiosa para garantizar la fiabilidad y relevancia de los resultados obtenidos.
"""

Null_stats=[]
unique_stats=[]
total=data.count()
for i,n in data.dtypes:
    print(f"Column {i}")
    Null_stats.append([i,(data.filter(F.col(i).isNull()).count())/total]) # Conteo de nulos
    if n == "string":
        unique_stats.append([i,[ j[0] for j in data.select(i).distinct().collect()][:10]]) # Conteo de Valores únicos

"""Ahora usaremos la función summary() del df transformado para obtener la distribución de las variables. Es relevante señalar que en los campos de Ciudad, Tipo de Propiedad y Residencial, la mayoría de los datos son valores nulos según este análisis. Además, se observa que en el resumen se combinan valores numéricos y de tipo cadena de caracteres."""

data.summary().show()

"""Se observa que la variable OPM Remarks tiene la mayoría de los datos vacíos. Esta información es fundamental para futuras implementaciones y análisis de datos, ya que indica que esta variable podría no ser relevante o estar incompletamente registrada en la base de datos."""

pd.DataFrame(Null_stats,columns=["Column","Percent of null data"]).sort_values("Percent of null data",ascending=False).head(6)

"""Durante el análisis, podemos ver que los valores únicos en varias variables coinciden con los nombres de las columnas reportadas. Por ejemplo, en el campo de ciudades (Town), se listan pueblos que se encuentran en el estado de Connecticut. Este descubrimiento es fundamental para comprender la naturaleza de los datos y prevenir interpretaciones incorrectas durante el análisis."""

pd.DataFrame(unique_stats)

"""Se realizó un proceso de reemplazo de los valores nulos en los campos de Tipo de Propiedad y Residencia. Este paso es crucial para asegurar que los análisis futuros se basen en datos más completos y precisos, lo que permite explorar de manera más exhaustiva las relaciones y tendencias presentes en el conjunto de datos."""

# Ajuste de información
data=data.withColumn("Property Type 2",F.col("Property Type")) # Columna adicional
data=data.fillna("No Information", subset=["Property Type"])
data=data.fillna("No Information", subset=["Residential Type"])

"""# Análisis preliminar

Utilizando la información recopilada hasta ahora, se realizó un análisis preliminar centrado en las tres variables económicas clave: Valor Total Tasado, Monto Total de Venta y Ratio de Venta. Se observó que el Ratio de Venta con respecto al Valor Tasado fue inferior a 1 en 2011, lo cual indica un comportamiento inusual en comparación con otros años y sugiere una variación significativa en el mercado inmobiliario durante ese periodo específico.
"""

# Identificación por tipo de propiedad
(data.groupBy("List Year").agg(F.sum("Assessed Value").alias("Total Assessed Value"),
                                   F.sum("Sale Amount").alias("Total Sale Amount"))
                                   .withColumn("Real Sale Ratio",F.col("Total Sale Amount")/F.col("Total Assessed Value")).orderBy("Real Sale Ratio").show())

"""En un análisis detallado de los tipos de propiedad, se descubrió que los apartamentos presentan el mejor Ratio de Venta en comparación con el Valor Tasado, con un valor de 10. No obstante, es crucial considerar que estos resultados deben ser sometidos a un análisis más exhaustivo. La razón radica en que esta observación podría estar afectada por la presencia de uno o varios valores atípicos en la categoría de apartamentos."""

(data.groupBy("Property Type 2").agg(F.sum("Assessed Value").alias("Total Assessed Value"),
                                   F.sum("Sale Amount").alias("Total Sale Amount"))
                                   .withColumn("Real Sale Ratio",F.col("Total Sale Amount")/F.col("Total Assessed Value")).orderBy("Real Sale Ratio",ascending=False).show())

"""En un análisis posterior de los tipos de residencia, se notó que todos los ratios permanecen por encima de 1.35. Es crucial mencionar que estos resultados surgen al considerar los valores de todos los años:"""

(data.groupBy("Residential Type").agg(F.sum("Assessed Value").alias("Total Assessed Value"),
                                   F.sum("Sale Amount").alias("Total Sale Amount"))
                                   .withColumn("Real Sale Ratio",F.col("Total Sale Amount")/F.col("Total Assessed Value")).show())

"""# 2011

Además de los análisis previos, se llevó a cabo una agrupación de los valores totales tasados y de venta para cada una de las ciudades en el año 2011. Durante esta revisión, se observó que en 20 ciudades, las ventas fueron inferiores a 1. Esto sugiere que en estos casos específicos, las propiedades se vendieron por un valor menor al valor tasado, posiblemente reflejando condiciones económicas o del mercado inmobiliario particulares de ese año y esas ubicaciones.
"""

#Análisis de año 2011 en pérdidas
(data.filter(F.col("List Year") == 2011).groupBy("Town").agg(F.sum("Assessed Value").alias("Total Assessed Value"),
                                   F.sum("Sale Amount").alias("Total Sale Amount"))
                                   .withColumn("Real Sale Ratio",F.col("Total Sale Amount")/F.col("Total Assessed Value"))
                                   .orderBy(F.col("Real Sale Ratio"))
                                   .show())

"""Como complemento a estos análisis, se presentan las siguientes gráficas, con el objetivo de identificar los puntos útiles a incluir en el desarrollo del tablero de BI.

# Visualizaciones

Scatterplot: Comparación de Ventas en 2011 y 2013

Para comenzar el análisis visual, se ha creado un scatterplot utilizando la librería Seaborn. En esta representación gráfica, se contrastan las ventas de propiedades entre los años 2011 y 2013. Esta comparativa muestra de forma clara la diferencia entre un año con ventas bajas (2011) y otro con ventas elevadas (2013). El scatterplot ayuda a identificar posibles patrones, valores atípicos y la distribución general de las ventas en estos dos años clave, ofreciendo una comprensión visual de la variabilidad en el mercado inmobiliario durante ese periodo.
"""

#Distribución de precios
df_plot=data.filter((F.col("List Year") == 2011) | (F.col("List Year") == 2013)).toPandas()

sns.scatterplot(data=df_plot,x="Assessed Value", y="Sale Amount",hue="List Year")

"""En el scatterplot presentado, se puede observar claramente el efecto de los outliers en cada uno de los años analizados. Es notable que en el año 2011, la propiedad con el precio tasado más alto se vendió a un precio significativamente menor, lo que se refleja en el punto atípico en el gráfico. Por otro lado, en el año 2013, estos casos de discrepancia entre el precio tasado y el precio de venta disminuyeron.

Boxplot: Distribución de Valores Tasados y de Ventas por Tipos de Propiedad

Para complementar el análisis visual, se presentan boxplots que ilustran la distribución de los valores tasados y de ventas para diferentes tipos de propiedad. Esta representación gráfica permite observar la variabilidad en los datos y proporciona información sobre la dispersión y posibles outliers en cada categoría.

Al examinar los boxplots, se observa una dispersión significativa en los valores tasados y de ventas para las propiedades sin información especificada, destacándose por su alta variabilidad en comparación con otras categorías. Sin embargo, esta variabilidad no se refleja de la misma manera en el ratio de ventas. En este caso, las propiedades de la categoría "Familia de cuatro" muestran una mayor dispersión en los ratios de ventas, indicando una variabilidad considerable en la relación entre los valores tasados y de ventas para esta categoría en particular.
"""

#Tamaño de figura
plt.figure(figsize=(15,10))
sns.boxplot(data=df_plot,y="Assessed Value",x="Property Type",showfliers=False,hue="List Year")

#Tamaño de figura
plt.figure(figsize=(15,10))
sns.boxplot(data=df_plot,y="Sales Ratio",x="Property Type",showfliers=False, hue="List Year")

"""# Mapas: Identificación de Patrones por Condado

Esta sección ha creado mapas interactivos diseñados para visualizar patrones geográficos específicos en cada condado de Connecticut. Para hacerlo, recopile los códigos FIPS de los condados de Connecticut y los ajuste al formato necesario para el modelo de mapa de Plotly utilizado en este proyecto.

Los mapas a continuación proporcionan una representación visual detallada de las ubicaciones geográficas de las ventas de propiedades y se utilizan para detectar tendencias y variaciones en las ventas de propiedades en todo el estado.
La representación espacial de los datos juega un papel clave en las variaciones regionales en el mercado de bienes raíces y es vital para la formulación de decisiones estratégicas y localizadas que se presentarán en secciones posteriores de este proyecto.
"""

data_loc=pd.read_excel("FipCodes.xlsx")
data_loc["FIPS"]= "0" + data_loc["FIPS"].astype(str)
data_loc.head(10)

"""Con la información de la delimitación de los condados de Estados Unidos dada, se subió un ejemplo utilizando Plotly. En este mapa interactivo se muestra la distribución de la población de cada condado, además se agregó otro indicador, el número de hombres.
Se muestra un ejemplo del sobre cómo presentar efectivamente valores adicionales sobre un mapa utilizando Plotly.
"""

#Cargado de información externa
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
                   dtype={"fips": str})

#Filtro por FIPS de Connecticut

list_connecticut=["09001",	"09003"	,"09005",	"09007",	"09009",	"09011",	"09013",	"09015"]

df = df[df["fips"].isin(list_connecticut)]

#Definición de objeto Plotly

fig = px.choropleth_mapbox(data_loc, geojson=counties, locations='FIPS', color='TOT_POP',
                           color_continuous_scale="Viridis",
                           hover_data='TOT_MALE',
                           #range_color=(0, 12),
                           labels={'TOT_POP':'Población',
                                   'TOT_MALE' : "Número Hombres"},
                           center={"lat": 41.599998, "lon": -72.699997},
                           mapbox_style="carto-positron"
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

"""De acuerdo con el contexto de la data actual, veo que la información es detallada por ciudad en vez de condado. Para manejar esta diferencia, he cargado una tabla adicional que proporciona la relación entre las ciudades y los condados correspondientes. Esta tabla es fundamental para asignar correctamente las ventas de propiedades a su ubicación geográfica."""

# Análisis por county - generación de tabla
df = spark.read.csv("CT_Municipalities.csv", header=True)
df.show()

"""Ahora realizamos la unión entre la base original para poder realizar la graficación de los principales indicadores económicos:"""

#Join entre tablas
df_join=data.join(df,on=(data.Town==df.Municipality),how="inner")

"""Usando la tabla df_join, creamos la base de datos para los mapas interactivos. En este paso, agrupamos la información por año y condado, incluyendo los valores de tasación de la vivienda, su valor de venta y la relación entre estos dos (la relación de venta respecto al valor tasado). Este proceso de agrupación ofrece una vista general de los datos para cada condado y año, fundamental para realizar análisis comparativos y descubrir patrones a lo largo del tiempo y en diversas ubicaciones geográficas:"""

df_map=df_join.groupBy("List Year","County").agg(
    F.sum("Assessed Value").alias("Assessed Value"),
    F.sum("Sale Amount").alias("Sale Amount")
).withColumn("Sale Ratio",F.col("Sale Amount")/F.col("Assessed Value"))
df_map.show()

#Conversión a pandas para realizar las gráficas
df_map_pd=df_map.toPandas()

"""Para el año 2019 se muestran las gráficas de cada uno de los indicadores mencionados, realizando un tratamiento de datos previo para poder utilizar los códigos FIPS que ya funcionaron en el caso base."""

df_plot=df_map_pd.merge(data_loc,left_on="County",right_on="CTYNAME")

"""En el primer mapa interactivo, podemos ver el Ratio de Ventas (relación de venta respecto al valor tasado) para cada uno de los condados en Connecticut. Este mapa permite visualizar las disparidades en las relaciones de ventas para diferentes áreas geográficas.

Es interesante observar que el condado correspondiente a 09015 (Windham) presenta un valor de ratio notablemente alto en comparación con los demás condados, con un ratio de 1.76. Esto contrasta con el condado inmediatamente siguiente, que tiene un ratio de 1.59. Esta diferencia destacada en el ratio de ventas para el condado de Windham sugiere un mercado inmobiliario particularmente dinámico o factores económicos específicos que podrían estar influyendo en las transacciones de propiedades en esa área.
"""

print(df_plot.columns)

fig = px.choropleth_mapbox(df_plot[df_plot["List Year"]==2019], geojson=counties, locations='FIPS', color='Sale Ratio',
                           color_continuous_scale="Viridis",
                           labels={'Sale Ratio':'Ratio de ventas'},
                           center={"lat": 41.599998, "lon": -72.699997},
                           mapbox_style="carto-positron"
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

"""Tras revisar detenidamente el valor tasado y vendido de los inmuebles en cada condado, encontramos un patrón significativo en Fairfield (09001). Este condado se distingue por su valor total superior al de los demás condados de Connecticut."""

fig = px.choropleth_mapbox(df_plot[df_plot["List Year"]==2019], geojson=counties, locations='FIPS', color='Assessed Value',
                           color_continuous_scale="Viridis",
                           labels={'Assessed Value':'Valor tasado'},
                           center={"lat": 41.599998, "lon": -72.699997},
                           mapbox_style="carto-positron"
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

fig = px.choropleth_mapbox(df_plot[df_plot["List Year"]==2019], geojson=counties, locations='FIPS', color='Sale Amount',
                           color_continuous_scale="Jet",
                           labels={'Sale Amount':'Valor vendido'},
                           center={"lat": 41.599998, "lon": -72.699997},
                           mapbox_style="carto-positron"
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

"""# Conclusiones

En este análisis se identificaron varios puntos clave para entender el mercado inmobiliario en Connecticut:

- Facilidad para manejar bases de datos: Se demostró la capacidad de gestionar y manipular grandes conjuntos de datos usando Pyspark y Pandas, lo que facilita el procesamiento y análisis eficiente de la información.

- Comportamiento diferencial por año y condado: Se observaron variaciones importantes en el comportamiento del mercado inmobiliario según el año y el condado, lo que resalta la importancia de analizar los datos específicamente para cada área geográfica y período de tiempo.

- Uso efectivo de mapas para patrones de venta: Se implementaron mapas interactivos que permiten una visualización rápida y precisa de los patrones de venta de propiedades por condado. Esta técnica sirvió para identificar tendencias geoespaciales y disparidades regionales en el mercado.

- Ideas clave para visualizaciones y filtros futuros: Se generaron ideas para las visualizaciones y los filtros a incorporar en futuras implementaciones. Estos incluyen la exploración detallada de tipos de propiedad, análisis comparativos por condado y la integración de datos adicionales para enriquecer el análisis.

- Oportunidades para el desarrollo de modelos de Machine Learning: Se identificaron oportunidades para el desarrollo de modelos de Machine Learning, especialmente al considerar variables como tipo de propiedad, condado y otros factores adicionales. Estos modelos pueden proporcionar insights predictivos valiosos para el mercado inmobiliario.

En resumen, este notebook proporciona una sólida base para futuros análisis y desarrollos en el campo del mercado inmobiliario en Connecticut. Las observaciones y conclusiones obtenidas aquí son esenciales para guiar el camino hacia una comprensión más profunda y precisa del mercado, lo que puede llevar a decisiones estratégicas informadas en el futuro.
"""

